Python assignment


Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
* Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
* Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [51]:
# Task 1: Unit Conversion

def convert_units(value, conversion_type):
    """
    Convert between different units of measurement.
    :param value: float, the numerical value to convert
    :param conversion_type: str, the type of conversion
    :return: float, the converted value
    """
    conversions = {
        "m_to_ft": 3.28084,
        "ft_to_m": 0.3048,
        "kg_to_lbs": 2.20462,
        "lbs_to_kg": 0.453592,
        "L_to_gal": 0.264172,
        "gal_to_L": 3.78541,
    }

    return value * conversions.get(conversion_type, 1)

# Function calls
print(convert_units(10, "m_to_ft"))  # 10 meters to feet
print(convert_units(5, "kg_to_lbs"))  # 5 kg to lbs

32.8084
11.0231


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
* The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
* Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.



In [54]:
def calculate(numbers, operation):
    """
    Perform various mathematical operations on a list of numbers.
    :param numbers: list of float, the numbers to process
    :param operation: str, the operation to perform
    :return: float, the result of the operation
    """
    if operation == "sum":
        return sum(numbers)
    elif operation == "average":
        return sum(numbers) / len(numbers) if numbers else 0
    elif operation == "max":
        return max(numbers)
    elif operation == "min":
        return min(numbers)
    else:
        return None

# Function calls
numbers_list = [1, 2, 3, 4, 5]
print(calculate(numbers_list, "sum"))  # Sum of numbers
print(calculate(numbers_list, "average"))  # Average
print(calculate(numbers_list, "max"))  # Maximum
print(calculate(numbers_list, "min"))  # Minimum

15
3.0
5
1


4.2 Exercise on List Manipulation:
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
* Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [55]:
def extract_every_other(lst):
    """Returns every other element from the list."""
    return lst[::2]

2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
* Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].



In [56]:
def get_sublist(lst, start, end):
    """Returns a sublist from start to end index (inclusive)."""
    return lst[start:end+1]

3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
* Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [57]:
def get_sublist(lst, start, end):
    """Returns a sublist from start to end index (inclusive)."""
    return lst[start:end+1]

4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
* Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [58]:
def reverse_list(lst):
    """Reverses a list using slicing."""
    return lst[::-1]

5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
* Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [59]:
def remove_first_last(lst):
    """Removes the first and last elements from a list."""
    return lst[1:-1]

6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
* Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [60]:
def get_first_n(lst, n):
    """Returns the first n elements of a list."""
    return lst[:n]

def get_last_n(lst, n):
    """Returns the last n elements of a list."""
    return lst[-n:]

7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
* Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [61]:
def reverse_skip(lst):
    """Returns every second element in reverse order starting from the second last."""
    return lst[-2::-2]

In [62]:
sample_list = [1, 2, 3, 4, 5, 6]
print(extract_every_other(sample_list))
print(get_sublist(sample_list, 2, 4))
print(reverse_list(sample_list))
print(remove_first_last(sample_list))
print(get_first_n(sample_list, 3))
print(get_last_n(sample_list, 2))
print(reverse_skip(sample_list))

[1, 3, 5]
[3, 4, 5]
[6, 5, 4, 3, 2, 1]
[2, 3, 4, 5]
[1, 2, 3]
[5, 6]
[5, 3, 1]


#4.3 Exercise on Nested List:
1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [64]:
def flatten(lst):
    """Flattens a nested list into a single list."""
    return [item for sublist in lst for item in (sublist if isinstance(sublist, list) else [sublist])]

2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
* Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [65]:
def access_nested_element(lst, indices):
    """Accesses a specific element in a nested list based on indices."""
    for index in indices:
        lst = lst[index]
    return lst

3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
* Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [66]:
def sum_nested(lst):
    """Computes the sum of all elements in a nested list."""
    if isinstance(lst, int):
        return lst
    return sum(sum_nested(sublist) if isinstance(sublist, list) else sublist for sublist in lst)


4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [67]:
def remove_element(lst, elem):
    """Removes all occurrences of elem from a nested list."""
    if isinstance(lst, list):
        return [remove_element(sublist, elem) for sublist in lst if sublist != elem]
    return lst

5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [68]:
def find_max(lst):
    """Finds the maximum element in a nested list."""
    if isinstance(lst, int):
        return lst
    return max(find_max(sublist) if isinstance(sublist, list) else sublist for sublist in lst)


6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
* Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
* Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
* Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [69]:


def count_occurrences(lst, elem):
    """Counts occurrences of an element in a nested list."""
    if isinstance(lst, int):
        return int(lst == elem)
    return sum(count_occurrences(sublist, elem) for sublist in lst)

def deep_flatten(lst):
    """Flattens a deeply nested list into a single list."""
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list

def average_nested(lst):
    """Calculates the average of all elements in a nested list."""
    flat_list = deep_flatten(lst)
    return sum(flat_list) / len(flat_list) if flat_list else 0


In [70]:
# Function calls
nested_list = [[1, 2], [3, [4, 5]], 6]
print(flatten(nested_list))
print(access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))
print(sum_nested(nested_list))
print(remove_element([[1, 2], [3, 2], [4, 5]], 2))
print(find_max(nested_list))
print(count_occurrences([[1, 2], [2, 3], [2, 4]], 2))
print(deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))
print(average_nested([[1, 2], [3, 4], [5, 6]]))

[1, 2, 3, [4, 5], 6]
6
21
[[1], [3], [4, 5]]
6
3
[1, 2, 3, 4, 5, 6, 7, 8]
3.5


In [71]:
import numpy as np

# Problem - 1: Array Creation:

1. Initialize an empty array with size 2X2.

In [ ]:
empty_array = np.empty((2,2))
print(empty_array)

[[1.44267317e-316 0.00000000e+000]
 [6.54516949e-310 5.33257700e-317]]


2. Initialize an all one array with size 4X2.


In [ ]:
ones_array = np.ones((4,2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
full_array = np.full((3,3), 7)  # Example fill value 7
print(full_array)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
given_array = np.array([[1,2],[3,4]])
zeros_like_array = np.zeros_like(given_array)
print(given_array)
print(zeros_like_array)

[[1 2]
 [3 4]]
[[0 0]
 [0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
ones_like_array = np.ones_like(given_array)
print(ones_like_array)

[[1 1]
 [1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print(numpy_array)

[1 2 3 4]


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
range_array = np.arange(10, 50)
print(range_array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
matrix_3x3 = np.arange(9).reshape(3,3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
random_array = np.random.random(30)
print(random_array)
mean_value = random_array.mean()
print("\n",mean_value)

[0.77144655 0.04545177 0.09969406 0.78354828 0.26960412 0.66563356
 0.04831878 0.26011247 0.61963862 0.79832743 0.47025778 0.27477891
 0.72692451 0.54877687 0.63947363 0.97426158 0.31786423 0.2179163
 0.27960066 0.67818369 0.4010579  0.85441863 0.60439311 0.0040604
 0.62642869 0.55549884 0.65955328 0.8118026  0.01065757 0.57369722]

 0.4863794010343214


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
random_matrix = np.random.random((10,10))
print(random_matrix,"\n")
min_value, max_value = random_matrix.min(), random_matrix.max()
print("Minimum value:", min_value)
print("Maximum value:", max_value)

[[0.65197098 0.62303836 0.72000062 0.42656405 0.92854956 0.83761898
  0.53441739 0.10987334 0.53991256 0.98188143]
 [0.65249082 0.19404919 0.79469224 0.1576105  0.86768435 0.89495253
  0.15692009 0.02913269 0.31380365 0.51742574]
 [0.24755388 0.4142354  0.18878374 0.31520225 0.36516218 0.96698401
  0.23200032 0.25218185 0.91445495 0.63622732]
 [0.10668646 0.172567   0.672096   0.77243494 0.17407715 0.46670806
  0.63405764 0.65829559 0.69696566 0.67222339]
 [0.58587918 0.39401618 0.56458373 0.93320042 0.19442112 0.4893101
  0.82529289 0.55860098 0.25975527 0.13815241]
 [0.11045421 0.98862953 0.9421213  0.27300077 0.83430703 0.29049054
  0.71753791 0.43735973 0.92713344 0.28153763]
 [0.30656898 0.21511126 0.20067758 0.89869921 0.30073571 0.96726391
  0.57018105 0.39795715 0.50969752 0.21055031]
 [0.7324855  0.93118272 0.68243982 0.50812473 0.31910527 0.48624651
  0.08037313 0.36163861 0.03162879 0.91643096]
 [0.87391921 0.74801012 0.61133244 0.8817371  0.91214115 0.58055181
  0.1079988  

6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
zero_array = np.zeros(10)
print(zero_array)
print("\n")
zero_array[4] = 1
print(zero_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
arr = np.array([1,2,0,0,4,0])
print(arr)
print("\n")
reversed_arr = arr[::-1]
print(reversed_arr)

[1 2 0 0 4 0]


[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
border_array = np.ones((5,5))
print(border_array)
print("\n")
border_array[1:-1, 1:-1] = 0
print(border_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
checkerboard = np.zeros((8,8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Problem - 3: Array Operations:

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
# Problem - 3: Array Operations
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])
sum_arrays = x + y
print("Addition \n",sum_arrays)
sub_arrays = x - y
print("Subraction \n",sub_arrays)
mul_arrays = x * y
print("Multiplication \n",mul_arrays)

print("\n")

squared_array = x ** 2
print("Squared array \n",squared_array)

print("\n")

dot_vw = np.dot(v, w)
print("v and w dot product \n",dot_vw)

dot_xv = np.dot(x, v)
print("v and x dot product \n",dot_xv)

dot_xy = np.dot(x, y)
print("x and y dot product \n",dot_xy)

print("\n")

x_y_concat = np.concatenate((x, y), axis=0)
print("x and y concat \n",x_y_concat)

v_w_concat = np.column_stack((v, w))
print("v and w concat \n",v_w_concat)




Addition 
 [[ 6  8]
 [10 13]]
Subraction 
 [[-4 -4]
 [-4 -3]]
Multiplication 
 [[ 5 12]
 [21 40]]


Squared array 
 [[ 1  4]
 [ 9 25]]


v and w dot product 
 219
v and x dot product 
 [29 77]
x and y dot product 
 [[19 22]
 [50 58]]


x and y concat 
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w concat 
 [[ 9 11]
 [10 12]]


In [ ]:
# x_v_concat = np.concatenate((x, v), axis=0)  # Raises error: shape mismatch

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

# Problem - 4: Matrix Operations:

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A^−1 = I.
2. Prove A*B ̸= B*A.
3. Prove (AB)^T = B^T*A^T

In [ ]:
# Problem - 4: Matrix Operations
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
A_inv = np.linalg.inv(A)
identity_proof = np.dot(A, A_inv)
AB = np.dot(A, B)
BA = np.dot(B, A)
AB_T = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("Inverse of A")
print(A_inv)
print("\n")
print("Identity matrix result")
print(identity_proof)
print("\n")
print("A.B")
print(AB)
print("\n")
print("B.A")
print(BA)
print("\n")
print("AB.T")
print(AB_T)
print("\n")
print("B.T.A.T")
print(BT_AT)
print("\n")

Inverse of A
[[-2.    1.  ]
 [ 1.75 -0.75]]


Identity matrix result
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


A.B
[[23 13]
 [51 29]]


B.A
[[36 44]
 [13 16]]


AB.T
[[23 51]
 [13 29]]


B.T.A.T
[[23 51]
 [13 29]]




Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1 <br>
x − y + 2z = −3 <br>
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [ ]:
# Solving Linear Equations
print("In form AX=B")
coeff_matrix = np.array([[2,-3,1], [1,-1,2], [3,1,-1]])
print("A\n",coeff_matrix)
const_matrix = np.array([-1,-3,9])
print("B\n",const_matrix)

In form AX=B
A
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
B
 [-1 -3  9]


Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [ ]:
solution = np.linalg.solve(coeff_matrix, const_matrix)
print("X\n",solution)

X
 [ 2.  1. -2.]


In [ ]:
import time

# 10.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

1. Element-wise Addition:
* Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
* Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:


# Create list1, list2, numpy_arr1 and numpy_arr2
size = 1000000  # or any desired size for your lists
list1 = [i for i in range(size)]
list2 = [i * 2 for i in range(size)]
numpy_arr1 = np.array(list1)
numpy_arr2 = np.array(list2)


# Element-wise Addition
start_time = time.time()
list_add = [list1[i] + list2[i] for i in range(size)]
list_add_time = time.time() - start_time

start_time = time.time()
numpy_add = numpy_arr1 + numpy_arr2
numpy_add_time = time.time() - start_time

print("List Addition Time:", list_add_time)
print("NumPy Addition Time:", numpy_add_time)

List Addition Time: 0.09384799003601074
NumPy Addition Time: 0.009604454040527344


2. Element-wise Multiplication
* Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
* Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
# Element-wise Multiplication
start_time = time.time()
list_mult = [list1[i] * list2[i] for i in range(size)]
list_mult_time = time.time() - start_time

start_time = time.time()
numpy_mult = numpy_arr1 * numpy_arr2
numpy_mult_time = time.time() - start_time

print("List Multiplication Time:", list_mult_time)
print("NumPy Multiplication Time:", numpy_mult_time)

List Multiplication Time: 0.18908023834228516
NumPy Multiplication Time: 0.007491111755371094


3. Dot Product
* Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
* Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
# Dot Product
start_time = time.time()
list_dot = sum(list1[i] * list2[i] for i in range(size))
list_dot_time = time.time() - start_time

start_time = time.time()
numpy_dot = np.dot(numpy_arr1, numpy_arr2)
numpy_dot_time = time.time() - start_time

print("List Dot Product Time:", list_dot_time)
print("NumPy Dot Product Time:", numpy_dot_time)

List Dot Product Time: 0.09543323516845703
NumPy Dot Product Time: 0.0017178058624267578


4. Matrix Multiplication

* Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

* Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [ ]:
# Matrix Multiplication
matrix_size = 1000
list_matrix1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
list_matrix2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]

start_time = time.time()
result_matrix = [[sum(a*b for a, b in zip(row, col)) for col in zip(*list_matrix2)] for row in list_matrix1]
list_matrix_time = time.time() - start_time

numpy_matrix1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
numpy_matrix2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)

start_time = time.time()
numpy_matrix_mult = np.dot(numpy_matrix1, numpy_matrix2)
numpy_matrix_time = time.time() - start_time

print("List Matrix Multiplication Time:", list_matrix_time)
print("NumPy Matrix Multiplication Time:", numpy_matrix_time)

List Matrix Multiplication Time: 170.18989396095276
NumPy Matrix Multiplication Time: 1.702852487564087
